hack_site/hack_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

hack_site/home/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register(r'points-of-interest', PointOfInterestViewSet)
router.register(r'routes', RouteViewSet)


urlpatterns = [
    path('', home_view, name='home'),
    path('api/', include(router.urls)),
    path('complaints/', complaint_view, name="complaints"),
    path('map/', map_view, name='map_view'),
    path('pass/', pass_view, name='pass_view')
]

hack_site/home/models.py
from django.db import models

class Complaint(models.Model):
    # Auto-increment ID field is added automatically by Django as the primary key
    filer_name = models.CharField(max_length=100, verbose_name="Filer Name")
    email_address = models.EmailField(verbose_name="Email Address")
    phone_number = models.CharField(max_length=20, verbose_name="Phone Number")
    reason_for_complaint = models.TextField(verbose_name="Reason for Complaint")

    def __str__(self):
        return f"Complaint by {self.filer_name}"
    
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Vendor(models.Model):
    name = models.CharField(max_length=255)
    categories = models.ManyToManyField(Category)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return self.name

class PointOfInterest(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name
    
class Pass(models.Model):
    name = models.CharField(max_length=100)
    county = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} ({self.county})"
    
class Route(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=7, help_text="Hex color code for the route")
    points = models.ManyToManyField(PointOfInterest, related_name='routes')

    def __str__(self):
        return self.name

hack_site/home/forms.py
from django import forms
from .models import *

class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['filer_name', 'email_address', 'phone_number', 'reason_for_complaint']

class VendorForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields = ['name', 'categories', 'email', 'phone_number']

class PassForm(forms.ModelForm):
    class Meta:
        model = Pass
        fields = ['name', 'county']  # 'id' is auto-generated and not included in the form

hack_site/home/views.py
from django.shortcuts import render, redirect
from .models import * 
from .forms import *
from .serializers import PointOfInterestSerializer, RouteSerializer
from rest_framework import viewsets

def home_view(request):
    template = 'home/index.html'
    context = {}
    vendors = Vendor.objects.all()
    context['vendors'] = vendors
    return render(request, template, context)

def complaint_view(request):
    template = 'home/complaints.html'
    context = {}
    complaints = Complaint.objects.all()
    context['complaints'] = complaints
    form = ComplaintForm()

    if request.method == 'POST':
        form = ComplaintForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('complaints')  # Redirect to a new URL after posting
    else:
        form = ComplaintForm()  # An empty form instance for GET request

    context['form'] = form

    return render(request, template, context)
    
def add_vendor_view(request):
    template = 'home/add_vendors.html'
    context = {}
    form = VendorForm()

    if request.method == 'POST':
        form = VendorForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('vendor')  # Redirect to a new URL after posting
    else:
        form = VendorForm()  # An empty form instance for GET request

    context['form'] = form

    return render(request, template, context)


class PointOfInterestViewSet(viewsets.ModelViewSet):
    queryset = PointOfInterest.objects.all()
    serializer_class = PointOfInterestSerializer

    
class RouteViewSet(viewsets.ModelViewSet):
    queryset = Route.objects.all()
    serializer_class = RouteSerializer

def map_view(request):
    points_of_interest = PointOfInterest.objects.all()
    routes = Route.objects.all()
    points_serializer = PointOfInterestSerializer(points_of_interest, many=True)
    routes_serializer = RouteSerializer(routes, many=True)
    context = {
        'points_data': points_serializer.data,
        'routes_data': routes_serializer.data
    }
    return render(request, 'home/map.html', context)  

def pass_view(request):
    template = 'home/new_pass.html'
    context = {}
    passes = Pass.objects.all()
    context['passes'] = passes

    form = PassForm()

    if request.method == 'POST':
        form = PassForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('pass_view')  # Redirect to a new URL after posting
    else:
        form = PassForm()

    context['form'] = form
    
    return render(request, template, context)

hack_site/home/templates/home/add_vendors.html
{% extends 'home/base.html' %}
{% block content %}
<h1>Add Vendor</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

hack_site/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'home/header.html' %}

<style>
    .gradient {
        background-color: #eeeeee;
        background-image: linear-gradient(180deg, #ffffff 0%, #abf774 100%);
    }
</style>

<body class="gradient">
    <div class="container">
        {% block content %}
        
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

{% include 'home/footer.html' %}

</html>

hack_site/home/templates/home/complaints.html
{% extends 'home/base.html' %}
{% block content %}
<h1>File a New Complaint</h1>
<form method="post" class="form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_filer_name">Name:</label>
        <input type="text" name="filer_name" id="id_filer_name" class="form-control" value="{{ form.filer_name.value|default_if_none:'' }}" required>
    </div>
    <div class="form-group">
        <label for="id_email_address">Email:</label>
        <input type="email" name="email_address" id="id_email_address" class="form-control" value="{{ form.email_address.value|default_if_none:'' }}" required>
    </div>
    <div class="form-group">
        <label for="id_phone_number">Phone Number:</label>
        <input type="text" name="phone_number" id="id_phone_number" class="form-control" value="{{ form.phone_number.value|default_if_none:'' }}" required>
    </div>
    <div class="form-group">
        <label for="id_reason_for_complaint">Reason for Complaint:</label>
        <textarea name="reason_for_complaint" id="id_reason_for_complaint" class="form-control" required>{{ form.reason_for_complaint.value|default_if_none:'' }}</textarea>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

hack_site/home/templates/home/footer.html
<footer>
    <div class="container">
        <p class="nav justify-content-center pb-3 mb-3">&copy; 2024 Team 2, Hackathon BG</p>
    </div>
</footer>

hack_site/home/templates/home/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hackathon</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid"> <!-- This will make it stretch across the whole width -->
        <header class="mb-4">
            <div class="row">
                <div class="card col-12 shadow" style="border-radius: 0px;">
                    <h2 class="py-3" style="text-align: center;">Bowling Green Subway System</h2>
                    <ul class="nav nav-pills justify-content-center">
                        <li class="nav-item btn"><a href="{% url 'home' %}" class="nav-link" aria-current="page">Home</a></li>
                        <li class="nav-item btn"><a href="{% url 'map_view' %}" class="nav-link">Map</a></li>
                        <li class="nav-item btn"><a href="{% url 'pass_view' %}" class="nav-link">Passes</a></li>
                        <li class="nav-item btn"><a href="{% url 'complaints' %}" class="nav-link">Complaints</a></li>
                    </ul>
                </div>
            </div>
        </header>
    </div>
</body>

</html>

hack_site/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<style>
    .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
    }

    @media (min-width: 768px) {
    .bd-placeholder-img-lg {
        font-size: 3.5rem;
    }
    }

    .b-example-divider {
    width: 100%;
    height: 3rem;
    background-color: rgba(0, 0, 0, .1);
    border: solid rgba(0, 0, 0, .15);
    border-width: 1px 0;
    box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
    }

    .bi {
    vertical-align: -.125em;
    fill: currentColor;
    }

    .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
    }

    .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
    --bd-violet-bg: #712cf9;
    --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

    --bs-btn-font-weight: 600;
    --bs-btn-color: var(--bs-white);
    --bs-btn-bg: var(--bd-violet-bg);
    --bs-btn-border-color: var(--bd-violet-bg);
    --bs-btn-hover-color: var(--bs-white);
    --bs-btn-hover-bg: #6528e0;
    --bs-btn-hover-border-color: #6528e0;
    --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
    --bs-btn-active-color: var(--bs-btn-hover-color);
    --bs-btn-active-bg: #5a23c8;
    --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
    z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
    display: block !important;
    }
</style>

<div class="col-lg-8 mx-auto p-4 py-md-5">

    <main>
        <h1 class="text-body-emphasis">About</h1>
        <hr class="col-3 col-md-2 mb-2">

        <p>
            This Django Website Application was made as a future solution to be used in conjunction with future 
            Bowling Green, KY transportation upgrades to allow for residents an easier way to access newly built 
            subway/railway stations. These stations would not only allow residents another option for city travel, 
            but would also attract new businesses to build alongside these station hubs for increased city growth.
        </p>

        <div class="row g-5">
            <div class="col-md-6">
            <h2 class="text-body-emphasis">Software Tools</h2>
            <hr class="col-3 col-md-8 mb-2">

            <p>Our team utilized several different software tools, packages, and APIs to accomplish this site. The following is a list:</p>
                <ul class="list-unstyled ps-0">
                    <li>
                        <span class="icon-link mb-1">
                            <svg class="bi" width="16" height="16"><use xlink:href="#arrow-right-circle"/></svg>
                            Python 3.12.3
                        </span>
                    </li>
                    <li>
                        <span class="icon-link mb-1">
                            <svg class="bi" width="16" height="16"><use xlink:href="#arrow-right-circle"/></svg>
                            Django==5.0.6 
                        </span>
                    </li>
                    <li>
                        <span class="icon-link mb-1">
                            <svg class="bi" width="16" height="16"><use xlink:href="#arrow-right-circle"/></svg>
                            django-easy-maps==1.1.3
                        </span>
                    </li>
                    <li>
                        <span class="icon-link mb-1">
                            <svg class="bi" width="16" height="16"><use xlink:href="#arrow-right-circle"/></svg>
                            djangorestframework==3.15.1
                        </span>
                    </li>
                    <li>
                        <span class="icon-link mb-1">
                            <svg class="bi" width="16" height="16"><use xlink:href="#arrow-right-circle"/></svg>
                            Bootstrap for styling
                        </span>
                    </li>
                    
                </ul>
            </div>

            <div class="col-md-6">
                <h2 class="text-body-emphasis">Links</h2>
                <hr class="col-3 col-md-4 mb-2">
                <p>Read more detailed instructions and documentation with the website.</p>
                <ul class="list-unstyled ps-0">
                    <li>
                    <a class="icon-link mb-1" href="https://github.com/cylissama/hackathon">
                        <svg class="bi" width="16" height="16"><use xlink:href="#arrow-right-circle"/></svg>
                        Github Link
                    </a>
                    </li>
                </ul>
            </div>
        </div>
    </main>

</div>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

{% endblock %}

hack_site/home/templates/home/map.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title style="text-align: center;">Bowling Green, KY Map</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <style>
        #map {
            height: 600px;
            width: 100%;
        }
    </style>
</head>

<div class="card shadow" style="border-radius: 20px;">
<body>
    <h1 style="text-align: center; margin-top: 10px; margin-bottom: 10px;">Subway Routes</h1>
    <div id="map"></div>
    <script>
        var map = L.map('map').setView([36.9903, -86.4436], 13);

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
        }).addTo(map);

        // Array to store LatLng pairs
        var latLngs = [];

        // Fetch points of interest from the API
        fetch('/api/points-of-interest/')
            .then(response => response.json())
            .then(pointsOfInterest => {
                pointsOfInterest.forEach(point => {
                    var latLng = [point.latitude, point.longitude];
                    latLngs.push(latLng);  // Add coordinates to latLngs array
                    L.marker(latLng)
                        .addTo(map)
                        .bindPopup(`<b>${point.name}</b><br>${point.description}`);
                });

                // Optional: Adjust the map view to fit all points
                if (latLngs.length > 0) {
                    map.fitBounds(latLngs);
                }
            });

        // Fetch routes from the API
        fetch('/api/routes/')
            .then(response => response.json())
            .then(routes => {
                routes.forEach(route => {
                    var routeLatLngs = route.points.map(point => [point.latitude, point.longitude]);
                    L.polyline(routeLatLngs, {
                        color: route.color,  // Use the route's color
                        weight: 5,
                        opacity: 0.7
                    }).addTo(map);
                });
            });
    </script>
</body>
</div>

</html>
{% endblock %}

hack_site/home/templates/home/new_pass.html
{% extends 'home/base.html' %}
{% block content %}
<h1>Sign up for a Transportation Pass</h1>
<form method="post" class="form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name:</label>
        <input type="text" name="name" id="id_name" class="form-control" value="{{ form.name.value|default_if_none:'' }}" required>
    </div>
    <div class="form-group">
        <label for="id_county">County:</label>
        <input type="text" name="county" id="id_county" class="form-control" value="{{ form.county.value|default_if_none:'' }}" required>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}